version: 0.2

phases:
  install:
    commands:
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 891377361876.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t ia-leo .
      - docker tag ia-leo:latest 891377361876.dkr.ecr.us-west-2.amazonaws.com/ai-leo:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 891377361876.dkr.ecr.us-west-2.amazonaws.com/ai-leo:latest

artifacts:
  files:
    - '**/*'

