apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi-app
  ports:
    - protocol: TCP
      port: 80  # Exposes port 80 on the Service
      targetPort: 5000  # Routes traffic to port 5000 on the pods (where your FastAPI app is listening)
  type: LoadBalancer  # Depending on your setup, change to NodePort or ClusterIP if needed